openapi: 3.0.1
info:
  title: LabSq API
  description: This is an api-spec for `LabSqApi`.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Mothusi Molorane
    email: molorane.mothusi@gmail.com
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: 0.0.1
servers:
  - url: http://192.168.0.157:2021/labsq/api
    description: Generated server url
tags:
  - name: Employee
    description: Api operations for employee
paths:


  # EmployeeS
  /v1/employees:
    get:
      tags:
        - Employee
      summary: Retrieve Employee
      description: Retrieve Employee
      operationId: retrieve-Employee
      responses:
        '200':
          description: Retrieve Employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
            '*/*':
              schema:
                $ref: '#/components/schemas/Employee'
        '204':
          description: No Content
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                type: string
            '*/*':
              schema:
                type: string
    post:
      tags:
        - Employee
      summary: Add OAuth Employee
      description: Add OAuth Employee
      operationId: add-oauth-Employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Add Employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
            '*/*':
              schema:
                $ref: '#/components/schemas/Employee'
    put:
      tags:
        - Employee
      summary: Update Employee
      description: Update an Employee
      operationId: update-Employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Update Employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
            '*/*':
              schema:
                $ref: '#/components/schemas/Employee'

# SCHEMAS
components:
  schemas:
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
    Address:
      type: object
      properties:
        id:
          type: integer
          format: int64
        province:
          type: string