openapi: 3.0.1
info:
  title: LabSq API
  description: This is an api-spec for `LabSqApi`.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Mothusi Molorane
    email: molorane.mothusi@gmail.com
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: 0.0.1
servers:
  - url: http://localhost:8080/javaspace/api
    description: Generated server url
tags:
  - name: Employee
    description: Api operations for employee
paths:


  # Employee
  /v1/employees:
    get:
      tags:
        - Employee
      summary: Get Employee
      description: Get Employee
      operationId: get-employees
      responses:
        '200':
          description: Retrieve Employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
            '*/*':
              schema:
                $ref: '#/components/schemas/Employee'
        '204':
          description: No Content
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                type: string
            '*/*':
              schema:
                type: string

# SCHEMAS
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        id:
          type: integer
          format: int64
        province:
          type: string