spring:
  sql:
    init:
      mode: always
  datasource:
    username: root
    password: blessing
    url: jdbc:mysql://localhost:3306/JavaSpace?serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true