insert into employee (first_name,last_name) values ('Keith', 'Donald');
insert into employee (first_name,last_name) values ('Dollie', 'Adams');
insert into employee (first_name,last_name) values ('Cornelia', 'Andresen');
insert into employee (first_name,last_name) values ('Coral', 'Betancourt');
insert into employee (first_name,last_name) values ('Chad', 'Cobbs');
insert into employee (first_name,last_name) values ('Michael', 'Feller');
insert into employee (first_name,last_name) values ('Michael', 'Grover');
insert into employee (first_name,last_name) values ('John', 'Howard');
insert into employee (first_name,last_name) values ('Ida', 'Ketterer');
insert into employee (first_name,last_name) values ('Laina', 'Ochoa Lucero');
insert into employee (first_name,last_name) values ('Wesley', 'Mayo');
insert into employee (first_name,last_name) values ('Leslie', 'Mcclary');
insert into employee (first_name,last_name) values ('John', 'Mudra');
insert into employee (first_name,last_name) values ('Pietronella', 'Nielsen');
insert into employee (first_name,last_name) values ('John', 'Oleary');
insert into employee (first_name,last_name) values ('Glenda', 'Smith');
insert into employee (first_name,last_name) values ('Willemina', 'Thygesen');
insert into employee (first_name,last_name) values ('Antje', ' Vogt');
insert into employee (first_name,last_name) values ('Weber', 'Julia');
insert into employee (first_name,last_name) values ('Williams', 'Mark');
insert into employee (first_name,last_name) values ('Christine', 'Wilson');

insert into address (emp_id,province) values (1, 'Freetown');
insert into address (emp_id,province) values (2, 'Kigali');
insert into address (emp_id,province) values (3, 'Lome');
insert into address (emp_id,province) values (4, 'Lilongwe');
insert into address (emp_id,province) values (5, 'Pretoria');
insert into address (emp_id,province) values (6, 'Tripoli');
insert into address (emp_id,province) values (7, 'Maseru');
insert into address (emp_id,province) values (8, 'Nairobi');
insert into address (emp_id,province) values (9, 'Lusaka');
insert into address (emp_id,province) values (10, 'Moscow');
insert into address (emp_id,province) values (10, 'Moscow');
insert into address (emp_id,province) values (11, 'Mbabane');
insert into address (emp_id,province) values (12, 'Gaborone');
insert into address (emp_id,province) values (13, 'Harare');
insert into address (emp_id,province) values (14, 'Cairo');
insert into address (emp_id,province) values (15, 'Maputo');
insert into address (emp_id,province) values (16, 'Windhoek');
insert into address (emp_id,province) values (17, 'Kampala');
insert into address (emp_id,province) values (18, 'Dar es Salaam');
insert into address (emp_id,province) values (19, 'Addis Abba');
insert into address (emp_id,province) values (20, 'Abuja');
insert into address (emp_id,province) values (20, 'Lagos');